[package]
name = "freya-icons-example"
publish = false
version = "0.0.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "crates/codegen",
    "crates/lib",
]

[workspace.dependencies]
dioxus = { version = "0.6", features = ["macro"], default-features = false }
freya = "0.3"

[dev-dependencies]
freya-icons = { path = "./crates/lib", features = ["bootstrap"] }
dioxus = { workspace = true }
freya = { workspace = true }